services:
    mongo:
        container_name: mongodb
        restart: unless-stopped
        image: mongo
        ports:
            - 27017:27017
        volumes:
            - ./mongodata:/data/db
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example
#  mongo-express:
#    image: mongo-express
#    restart: unless-stopped
#    ports:
#      - 8081:8081
#    environment:
#      ME_CONFIG_MONGODB_ADMINUSERNAME: root
#      ME_CONFIG_MONGODB_ADMINPASSWORD: example
#      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
