services:
    backend:
        build: server
        container_name: gql-server
        restart: always
        ports:
            - 5000:5000
        volumes:
            - ./server:/app
            - /app/node_modules
        depends_on:
            - mongo
        networks:
            - express-mongo
            - react-express
    mongo:
        container_name: mongodb
        restart: unless-stopped
        image: mongo
        ports:
            - 27017:27017
        volumes:
            - ./mongodata:/data/db
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example
        networks:
            - express-mongo

#  mongo-express:
#    image: mongo-express
#    restart: unless-stopped
#    ports:
#      - 8081:8081
#    environment:
#      ME_CONFIG_MONGODB_ADMINUSERNAME: root
#      ME_CONFIG_MONGODB_ADMINPASSWORD: example
#      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

networks:
    react-express:
        external: true
    express-mongo:
        external: true
